#!/bin/sh

set

config=/usr/local/etc/miredo.conf
[ -f ${config}.sample ] && (
       [ -f ${config} ] || cp ${config}.sample ${config}
)

sudo chown -R root:wheel /Library/LaunchDaemons/miredo.plist \
                         /usr/local/sbin/miredo \
                         /usr/local/etc/miredo.conf


sudo launchctl load /Library/LaunchDaemons/miredo.plist
