#!/bin/sh

set

[ -f /usr/etc/miredo.conf ] && (
	[ -f /etc/miredo.conf ] || cp /usr/etc/miredo.conf /etc/miredo.conf
)

[ -f /usr/local/etc/miredo.conf ] && (
	[ -f /etc/miredo.conf ] || cp /usr/local/etc/miredo.conf /etc/miredo.conf
)

[ -f /etc/miredo.conf.sample ] && (
	[ -f /etc/miredo.conf ] || cp /etc/miredo.conf.sample /etc/miredo.conf
)

sudo chown -R root:wheel /Library/LaunchDaemons/miredo.plist /usr/sbin/miredo /etc/miredo.conf


sudo launchctl load /Library/LaunchDaemons/miredo.plist
